REDIRECT_URI: http://localhost:3039/login

grade:
  senior2:
    generation: 47
    display_name: 高2
    type: senior
  senior1:
    generation: 48
    display_name: 高1
    type: senior
  junior3:
    generation: 49
    display_name: 中3
    type: junior
  junior2:
    generation: 50
    display_name: 中2
    type: junior
  junior1:
    generation: 51
    display_name: 中1
    type: junior
