REDIRECT_URI: https://tokowo.jp/login
ORIGINS:
- https://tokowo.jp
DEBUG: false
AUTO_INSERT_TIME: '21:00'
SCHEDULER_ENABLED: false
grade:
  senior3:
    generation: 47
    display_name: 高3
    type: senior
  senior2:
    generation: 48
    display_name: 高2
    type: senior
  senior1:
    generation: 49
    display_name: 高1
    type: senior
  junior3:
    generation: 50
    display_name: 中3
    type: junior
  junior2:
    generation: 51
    display_name: 中2
    type: junior
  junior1:
    generation: 52
    display_name: 中1
    type: junior
