"""Add attendance disabled flag and log type.

Revision ID: 6085dc70f5b0
Revises: a628de5652ee
Create Date: 2026-04-27 17:17:56.058935

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa

from app.database import models


# revision identifiers, used by Alembic.
revision = '6085dc70f5b0'
down_revision = 'a628de5652ee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('attendance_logs', sa.Column('type', sa.String(), nullable=False))
    op.add_column('attendances', sa.Column('is_disabled', sa.Boolean(), nullable=False))
    op.create_unique_constraint(None, 'generation_roles', ['generation', 'role_id'])
    op.create_unique_constraint(None, 'member_groups', ['member_id', 'group_id'])
    op.create_unique_constraint(None, 'member_roles', ['member_id', 'role_id'])
    op.create_unique_constraint(None, 'permission_implies', ['parent_permission_id', 'child_permission_id'])
    op.create_unique_constraint(None, 'role_permissions', ['role_id', 'permission_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'role_permissions', type_='unique')
    op.drop_constraint(None, 'permission_implies', type_='unique')
    op.drop_constraint(None, 'member_roles', type_='unique')
    op.drop_constraint(None, 'member_groups', type_='unique')
    op.drop_constraint(None, 'generation_roles', type_='unique')
    op.drop_column('attendances', 'is_disabled')
    op.drop_column('attendance_logs', 'type')
    # ### end Alembic commands ###
