"""init

Revision ID: 8f7e2cc9a9e2
Revises: 
Create Date: 2026-03-07 21:41:17.331808

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa
from sqlalchemy import text



# revision identifiers, used by Alembic.
revision = '8f7e2cc9a9e2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('member_roles',
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('member_id', 'role_id'),
    sa.UniqueConstraint('member_id', 'role_id')
    )
    op.create_table('role_permissions',
    sa.Column('role_id', sa.Uuid(), nullable=False),
    sa.Column('permission_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id'),
    sa.UniqueConstraint('role_id', 'permission_id')
    )
    op.create_unique_constraint(None, 'member_groups', ['member_id', 'group_id'])

    # members.felica_idm may already be removed in some DBs; drop only if exists
    conn = op.get_bind()
    exists = conn.execute(
        text(
            """
            select 1
            from information_schema.columns
            where table_schema='public'
              and table_name='members'
              and column_name='felica_idm'
            """
        )
    ).first()
    if exists:
        op.drop_column('members', 'felica_idm')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('members', sa.Column('felica_idm', sa.VARCHAR(length=23), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'member_groups', type_='unique')
    op.drop_table('role_permissions')
    op.drop_table('member_roles')
    op.drop_table('roles')
    op.drop_table('permissions')
    # ### end Alembic commands ###


