"""create_attendance_column

Revision ID: a123253cc717
Revises: a1b2c3d4e5f6
Create Date: 2026-03-18 10:11:04.160967

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'a123253cc717'
down_revision = 'a1b2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('attendance_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('member_id', sa.Uuid(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('terminal_member_id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['terminal_member_id'], ['members.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('attendances', sa.Column('first_tap_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('attendances', sa.Column('last_tap_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('attendances', 'last_tap_at')
    op.drop_column('attendances', 'first_tap_at')
    op.drop_table('attendance_logs')
    # ### end Alembic commands ###
