"""add felica_idm column to member table

Revision ID: ec35e27338ac
Revises: b1a2c3d4e5f6
Create Date: 2026-03-13 10:42:13.041916

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa



# revision identifiers, used by Alembic.
revision = 'ec35e27338ac'
down_revision = 'b1a2c3d4e5f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'generation_roles', ['generation', 'role_id'])
    op.create_unique_constraint(None, 'member_roles', ['member_id', 'role_id'])
    op.add_column('members', sa.Column('felica_idm', sa.String(length=23), nullable=True))
    op.create_unique_constraint(None, 'permission_implies', ['parent_permission_id', 'child_permission_id'])
    op.create_unique_constraint(None, 'role_permissions', ['role_id', 'permission_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'role_permissions', type_='unique')
    op.drop_constraint(None, 'permission_implies', type_='unique')
    op.drop_column('members', 'felica_idm')
    op.drop_constraint(None, 'member_roles', type_='unique')
    op.drop_constraint(None, 'generation_roles', type_='unique')
    # ### end Alembic commands ###
